plugins:
  workflow_enabled:
    client: true
    default: true
  workflow_openai_api_key:
    client: false
    default: ''
  workflow_ai_prompt_system:
    client: false
    default: ""
    type: string
  workflow_ai_model:
    client: false
    type: enum
    default: gpt-4o-mini
    choices:
      - gpt-3.5-turbo
      - gpt-4o
      - gpt-4o-mini
      - gpt-4-turbo
      - gpt-4
